# Generated by Django 5.1.4 on 2025-02-13 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("start_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("destination_address", models.CharField(max_length=255)),
                (
                    "destination_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "destination_lng",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("driver_assigned", "Driver Assigned"),
                            ("driver_en_route", "Driver En Route"),
                            ("arrived", "Arrived"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("history", models.JSONField(blank=True, default=list)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
