# Generated by Django 5.1.4 on 2025-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_alter_user_options_user_average_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_online",
        ),
        migrations.AddField(
            model_name="user",
            name="driver_status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("busy", "Busy"),
                ],
                default="offline",
                max_length=10,
                verbose_name="Driver Status",
            ),
        ),
    ]
