# Generated by Django 5.1.4 on 2025-05-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0007_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("ONLINE", "Online"), ("CASH", "Cash")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
